language: cpp
compiler:
  - gcc
  - clang
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libcurlpp-dev
      - libboost-all-dev
before_install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 60
script:
  - mkdir -p build && cd build
  - cmake -DWITH_EXAMPLES=ON ..
  - make VERBOSE=1
  - make install DESTDIR=install
  - cd ..

before_deploy:
  - sudo apt-get install rpm
  - cd build
  - cp -v packages/gentoo/mastodon-cpp-0.0.0.ebuild mastodon-cpp-${TRAVIS_TAG}.ebuild
  - cmake -DWITH_DEB=ON ..
  - make package
  - cmake -DWITH_DEB=OFF -DWITH_RPM=ON ..
  - make package
deploy:
  provider: releases
  api_key:
    secure: "rdEd2cytMZb6oS5DBuGKjaQoccspMWlrlr/fKpdJkhfLgFOXI6lWSEvtWSB8Gmej9J++0dZPGbQ6fhRuSRwMa7LM3c2yM7kqhfeKcQiFgol33UbMBPZU/OkohJJl49Bp32qwLUQpfeL7B6ukVkxv7XPetE0ks+29vGsEWLowjLj3jEvHTzucgvxblwCdshekYnMUH+4lkLoSqTenCjjTcRbKI7yLLlGSa92PudzrfeAsz0lV4GiXiMIffTPP9dOfi4ceRB4qkKxb35CZbZUjxlZoppghh1uFvi9GYsGseIQl/iGvOtzoUj6c5AoTEZeDa96pD1x/QpjVk2lPYqtmzfIgzIueQW/BUddwaUbzw/8dVTXMsgy3ocTICqPic8LxNWjMGbt/v2E7wiY+TitNWqoNlgoZQjrlrYQ/21yoilvGfpnqRllzr4ofiHq4CI94kgxtuhd3De4O/aJvbrxj8liToqHSwX/taJHwV5rQ2Afl9vhTFgPWzyAbYXFNuulmG2ew6Q1ywyf+GXCPBk22w0IvLom5lqtFD/WSS0LFTzstDiDQEg/fnOo7bGzcQYQR5jq8hfj9EDaIZYek5BpNLeRmkqIbvtu6vwy4ufx3MIDR+69H1Xn5BlpXdhII7r4ZRKlUiw4mqHm76LPwoxLoWL36a+mySOgBxjAgJQdifYU="
  file:
    - "mastodon-cpp-${TRAVIS_TAG}.ebuild"
    - "libmastodon-cpp_${TRAVIS_TAG}-0_amd64.deb"
    - "libmastodon-cpp-${TRAVIS_TAG}-0.x86_64.rpm"
  skip_cleanup: true
  on:
    tags: true
    condition: $CC = gcc
